package com.billings.billingsystem.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.billings.billingsystem.model.SysAccountBean;
import com.billings.billingsystem.model.SysAccountBeanCriteria;

public interface SysAccountBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_account
     *
     * @mbggenerated
     */
    int countByExample(SysAccountBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_account
     *
     * @mbggenerated
     */
    int deleteByExample(SysAccountBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String sysAccountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_account
     *
     * @mbggenerated
     */
    int insert(SysAccountBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_account
     *
     * @mbggenerated
     */
    int insertSelective(SysAccountBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_account
     *
     * @mbggenerated
     */
    List<SysAccountBean> selectByExampleWithRowbounds(SysAccountBeanCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_account
     *
     * @mbggenerated
     */
    List<SysAccountBean> selectByExample(SysAccountBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_account
     *
     * @mbggenerated
     */
    SysAccountBean selectByPrimaryKey(String sysAccountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_account
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysAccountBean record, @Param("example") SysAccountBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_account
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysAccountBean record, @Param("example") SysAccountBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysAccountBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysAccountBean record);
}