package com.billings.billingsystem.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.billings.billingsystem.model.TradeFlowBean;
import com.billings.billingsystem.model.TradeFlowBeanCriteria;

public interface TradeFlowBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trade_flow
     *
     * @mbggenerated
     */
    int countByExample(TradeFlowBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trade_flow
     *
     * @mbggenerated
     */
    int deleteByExample(TradeFlowBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trade_flow
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer flowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trade_flow
     *
     * @mbggenerated
     */
    int insert(TradeFlowBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trade_flow
     *
     * @mbggenerated
     */
    int insertSelective(TradeFlowBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trade_flow
     *
     * @mbggenerated
     */
    List<TradeFlowBean> selectByExampleWithRowbounds(TradeFlowBeanCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trade_flow
     *
     * @mbggenerated
     */
    List<TradeFlowBean> selectByExample(TradeFlowBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trade_flow
     *
     * @mbggenerated
     */
    TradeFlowBean selectByPrimaryKey(Integer flowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trade_flow
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TradeFlowBean record, @Param("example") TradeFlowBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trade_flow
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TradeFlowBean record, @Param("example") TradeFlowBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trade_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradeFlowBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trade_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradeFlowBean record);
}