package com.billings.billingsystem.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.billings.billingsystem.model.UserDatumBean;
import com.billings.billingsystem.model.UserDatumBeanCriteria;
import com.billings.billingsystem.model.UserDatumBeanKey;

public interface UserDatumBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_datum
     *
     * @mbggenerated
     */
    int countByExample(UserDatumBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_datum
     *
     * @mbggenerated
     */
    int deleteByExample(UserDatumBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_datum
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(UserDatumBeanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_datum
     *
     * @mbggenerated
     */
    int insert(UserDatumBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_datum
     *
     * @mbggenerated
     */
    int insertSelective(UserDatumBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_datum
     *
     * @mbggenerated
     */
    List<UserDatumBean> selectByExampleWithRowbounds(UserDatumBeanCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_datum
     *
     * @mbggenerated
     */
    List<UserDatumBean> selectByExample(UserDatumBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_datum
     *
     * @mbggenerated
     */
    UserDatumBean selectByPrimaryKey(UserDatumBeanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_datum
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserDatumBean record, @Param("example") UserDatumBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_datum
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserDatumBean record, @Param("example") UserDatumBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_datum
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserDatumBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_datum
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserDatumBean record);
}