package com.hundsun.internet.billingsystem.bean.util;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.hundsun.internet.billingsystem.model.TradeFlowBean;

public class MyScoreBean implements Serializable {
	
	/**
	 * 本账户所查的流水账单号
	 */
	private List<TradeFlowBean> listTradeFlows;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score.create_datetime
     *
     * @mbggenerated
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score.updator
     *
     * @mbggenerated
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score.update_datetime
     *
     * @mbggenerated
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score.score_num
     *
     * @mbggenerated
     */
    private Integer scoreNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_score.good_luck_coin_num
     *
     * @mbggenerated
     */
    private Integer goodLuckCoinNum;
    

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_score
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score.user_id
     *
     * @return the value of tb_score.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score.user_id
     *
     * @param userId the value for tb_score.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score.state
     *
     * @return the value of tb_score.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score.state
     *
     * @param state the value for tb_score.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score.creator
     *
     * @return the value of tb_score.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score.creator
     *
     * @param creator the value for tb_score.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score.create_datetime
     *
     * @return the value of tb_score.create_datetime
     *
     * @mbggenerated
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score.create_datetime
     *
     * @param createDatetime the value for tb_score.create_datetime
     *
     * @mbggenerated
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score.updator
     *
     * @return the value of tb_score.updator
     *
     * @mbggenerated
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score.updator
     *
     * @param updator the value for tb_score.updator
     *
     * @mbggenerated
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score.update_datetime
     *
     * @return the value of tb_score.update_datetime
     *
     * @mbggenerated
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score.update_datetime
     *
     * @param updateDatetime the value for tb_score.update_datetime
     *
     * @mbggenerated
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score.score_num
     *
     * @return the value of tb_score.score_num
     *
     * @mbggenerated
     */
    public Integer getScoreNum() {
        return scoreNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score.score_num
     *
     * @param scoreNum the value for tb_score.score_num
     *
     * @mbggenerated
     */
    public void setScoreNum(Integer scoreNum) {
        this.scoreNum = scoreNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_score.good_luck_coin_num
     *
     * @return the value of tb_score.good_luck_coin_num
     *
     * @mbggenerated
     */
    public Integer getGoodLuckCoinNum() {
        return goodLuckCoinNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_score.good_luck_coin_num
     *
     * @param goodLuckCoinNum the value for tb_score.good_luck_coin_num
     *
     * @mbggenerated
     */
    public void setGoodLuckCoinNum(Integer goodLuckCoinNum) {
        this.goodLuckCoinNum = goodLuckCoinNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MyScoreBean other = (MyScoreBean) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreateDatetime() == null ? other.getCreateDatetime() == null : this.getCreateDatetime().equals(other.getCreateDatetime()))
            && (this.getUpdator() == null ? other.getUpdator() == null : this.getUpdator().equals(other.getUpdator()))
            && (this.getUpdateDatetime() == null ? other.getUpdateDatetime() == null : this.getUpdateDatetime().equals(other.getUpdateDatetime()))
            && (this.getScoreNum() == null ? other.getScoreNum() == null : this.getScoreNum().equals(other.getScoreNum()))
            && (this.getGoodLuckCoinNum() == null ? other.getGoodLuckCoinNum() == null : this.getGoodLuckCoinNum().equals(other.getGoodLuckCoinNum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreateDatetime() == null) ? 0 : getCreateDatetime().hashCode());
        result = prime * result + ((getUpdator() == null) ? 0 : getUpdator().hashCode());
        result = prime * result + ((getUpdateDatetime() == null) ? 0 : getUpdateDatetime().hashCode());
        result = prime * result + ((getScoreNum() == null) ? 0 : getScoreNum().hashCode());
        result = prime * result + ((getGoodLuckCoinNum() == null) ? 0 : getGoodLuckCoinNum().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", state=").append(state);
        sb.append(", creator=").append(creator);
        sb.append(", createDatetime=").append(createDatetime);
        sb.append(", updator=").append(updator);
        sb.append(", updateDatetime=").append(updateDatetime);
        sb.append(", scoreNum=").append(scoreNum);
        sb.append(", goodLuckCoinNum=").append(goodLuckCoinNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

	public List<TradeFlowBean> getListTradeFlows() {
		return listTradeFlows;
	}

	public void setListTradeFlows(List<TradeFlowBean> listTradeFlows) {
		this.listTradeFlows = listTradeFlows;
	}

}