package com.billings.billingsystem.model;

import java.io.Serializable;

public class UserDatumBean extends UserDatumBeanKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_datum.cur_score_num
     *
     * @mbggenerated
     */
    private Integer curScoreNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_datum.cur_good_luck_coin_num
     *
     * @mbggenerated
     */
    private Integer curGoodLuckCoinNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_datum.ret_score_num
     *
     * @mbggenerated
     */
    private Integer retScoreNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_datum.ret_good_luck_coin_num
     *
     * @mbggenerated
     */
    private Integer retGoodLuckCoinNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user_datum
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_datum.cur_score_num
     *
     * @return the value of tb_user_datum.cur_score_num
     *
     * @mbggenerated
     */
    public Integer getCurScoreNum() {
        return curScoreNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_datum.cur_score_num
     *
     * @param curScoreNum the value for tb_user_datum.cur_score_num
     *
     * @mbggenerated
     */
    public void setCurScoreNum(Integer curScoreNum) {
        this.curScoreNum = curScoreNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_datum.cur_good_luck_coin_num
     *
     * @return the value of tb_user_datum.cur_good_luck_coin_num
     *
     * @mbggenerated
     */
    public Integer getCurGoodLuckCoinNum() {
        return curGoodLuckCoinNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_datum.cur_good_luck_coin_num
     *
     * @param curGoodLuckCoinNum the value for tb_user_datum.cur_good_luck_coin_num
     *
     * @mbggenerated
     */
    public void setCurGoodLuckCoinNum(Integer curGoodLuckCoinNum) {
        this.curGoodLuckCoinNum = curGoodLuckCoinNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_datum.ret_score_num
     *
     * @return the value of tb_user_datum.ret_score_num
     *
     * @mbggenerated
     */
    public Integer getRetScoreNum() {
        return retScoreNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_datum.ret_score_num
     *
     * @param retScoreNum the value for tb_user_datum.ret_score_num
     *
     * @mbggenerated
     */
    public void setRetScoreNum(Integer retScoreNum) {
        this.retScoreNum = retScoreNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_datum.ret_good_luck_coin_num
     *
     * @return the value of tb_user_datum.ret_good_luck_coin_num
     *
     * @mbggenerated
     */
    public Integer getRetGoodLuckCoinNum() {
        return retGoodLuckCoinNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_datum.ret_good_luck_coin_num
     *
     * @param retGoodLuckCoinNum the value for tb_user_datum.ret_good_luck_coin_num
     *
     * @mbggenerated
     */
    public void setRetGoodLuckCoinNum(Integer retGoodLuckCoinNum) {
        this.retGoodLuckCoinNum = retGoodLuckCoinNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_datum
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserDatumBean other = (UserDatumBean) that;
        return (this.getDatumId() == null ? other.getDatumId() == null : this.getDatumId().equals(other.getDatumId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getCurScoreNum() == null ? other.getCurScoreNum() == null : this.getCurScoreNum().equals(other.getCurScoreNum()))
            && (this.getCurGoodLuckCoinNum() == null ? other.getCurGoodLuckCoinNum() == null : this.getCurGoodLuckCoinNum().equals(other.getCurGoodLuckCoinNum()))
            && (this.getRetScoreNum() == null ? other.getRetScoreNum() == null : this.getRetScoreNum().equals(other.getRetScoreNum()))
            && (this.getRetGoodLuckCoinNum() == null ? other.getRetGoodLuckCoinNum() == null : this.getRetGoodLuckCoinNum().equals(other.getRetGoodLuckCoinNum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_datum
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDatumId() == null) ? 0 : getDatumId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getCurScoreNum() == null) ? 0 : getCurScoreNum().hashCode());
        result = prime * result + ((getCurGoodLuckCoinNum() == null) ? 0 : getCurGoodLuckCoinNum().hashCode());
        result = prime * result + ((getRetScoreNum() == null) ? 0 : getRetScoreNum().hashCode());
        result = prime * result + ((getRetGoodLuckCoinNum() == null) ? 0 : getRetGoodLuckCoinNum().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_datum
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", curScoreNum=").append(curScoreNum);
        sb.append(", curGoodLuckCoinNum=").append(curGoodLuckCoinNum);
        sb.append(", retScoreNum=").append(retScoreNum);
        sb.append(", retGoodLuckCoinNum=").append(retGoodLuckCoinNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}