package com.hundsun.internet.billingsystem.model;

import java.io.Serializable;
import java.util.Date;

public class DatumBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_datum.datum_id
     *
     * @mbggenerated
     */
    private String datumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_datum.datum_date
     *
     * @mbggenerated
     */
    private Date datumDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_datum.max_flow_id
     *
     * @mbggenerated
     */
    private Integer maxFlowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_datum.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_datum.result
     *
     * @mbggenerated
     */
    private Integer result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_datum.create_datetime
     *
     * @mbggenerated
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_datum
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_datum.datum_id
     *
     * @return the value of tb_datum.datum_id
     *
     * @mbggenerated
     */
    public String getDatumId() {
        return datumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_datum.datum_id
     *
     * @param datumId the value for tb_datum.datum_id
     *
     * @mbggenerated
     */
    public void setDatumId(String datumId) {
        this.datumId = datumId == null ? null : datumId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_datum.datum_date
     *
     * @return the value of tb_datum.datum_date
     *
     * @mbggenerated
     */
    public Date getDatumDate() {
        return datumDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_datum.datum_date
     *
     * @param datumDate the value for tb_datum.datum_date
     *
     * @mbggenerated
     */
    public void setDatumDate(Date datumDate) {
        this.datumDate = datumDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_datum.max_flow_id
     *
     * @return the value of tb_datum.max_flow_id
     *
     * @mbggenerated
     */
    public Integer getMaxFlowId() {
        return maxFlowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_datum.max_flow_id
     *
     * @param maxFlowId the value for tb_datum.max_flow_id
     *
     * @mbggenerated
     */
    public void setMaxFlowId(Integer maxFlowId) {
        this.maxFlowId = maxFlowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_datum.state
     *
     * @return the value of tb_datum.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_datum.state
     *
     * @param state the value for tb_datum.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_datum.result
     *
     * @return the value of tb_datum.result
     *
     * @mbggenerated
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_datum.result
     *
     * @param result the value for tb_datum.result
     *
     * @mbggenerated
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_datum.create_datetime
     *
     * @return the value of tb_datum.create_datetime
     *
     * @mbggenerated
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_datum.create_datetime
     *
     * @param createDatetime the value for tb_datum.create_datetime
     *
     * @mbggenerated
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_datum
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DatumBean other = (DatumBean) that;
        return (this.getDatumId() == null ? other.getDatumId() == null : this.getDatumId().equals(other.getDatumId()))
            && (this.getDatumDate() == null ? other.getDatumDate() == null : this.getDatumDate().equals(other.getDatumDate()))
            && (this.getMaxFlowId() == null ? other.getMaxFlowId() == null : this.getMaxFlowId().equals(other.getMaxFlowId()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getResult() == null ? other.getResult() == null : this.getResult().equals(other.getResult()))
            && (this.getCreateDatetime() == null ? other.getCreateDatetime() == null : this.getCreateDatetime().equals(other.getCreateDatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_datum
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDatumId() == null) ? 0 : getDatumId().hashCode());
        result = prime * result + ((getDatumDate() == null) ? 0 : getDatumDate().hashCode());
        result = prime * result + ((getMaxFlowId() == null) ? 0 : getMaxFlowId().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getResult() == null) ? 0 : getResult().hashCode());
        result = prime * result + ((getCreateDatetime() == null) ? 0 : getCreateDatetime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_datum
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", datumId=").append(datumId);
        sb.append(", datumDate=").append(datumDate);
        sb.append(", maxFlowId=").append(maxFlowId);
        sb.append(", state=").append(state);
        sb.append(", result=").append(result);
        sb.append(", createDatetime=").append(createDatetime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}