package com.hundsun.internet.billingsystem.model;

import java.io.Serializable;
import java.util.Date;

public class TradeFlowBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade_flow.flow_id
     *
     * @mbggenerated
     */
    private Integer flowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade_flow.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade_flow.sys_account_id
     *
     * @mbggenerated
     */
    private String sysAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade_flow.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade_flow.create_datetime
     *
     * @mbggenerated
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade_flow.score_num
     *
     * @mbggenerated
     */
    private Integer scoreNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade_flow.good_luck_coin_num
     *
     * @mbggenerated
     */
    private Integer goodLuckCoinNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade_flow.order_num
     *
     * @mbggenerated
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade_flow.trade_type
     *
     * @mbggenerated
     */
    private Integer tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade_flow.batch_code
     *
     * @mbggenerated
     */
    private String batchCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_trade_flow
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade_flow.flow_id
     *
     * @return the value of tb_trade_flow.flow_id
     *
     * @mbggenerated
     */
    public Integer getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade_flow.flow_id
     *
     * @param flowId the value for tb_trade_flow.flow_id
     *
     * @mbggenerated
     */
    public void setFlowId(Integer flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade_flow.user_id
     *
     * @return the value of tb_trade_flow.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade_flow.user_id
     *
     * @param userId the value for tb_trade_flow.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade_flow.sys_account_id
     *
     * @return the value of tb_trade_flow.sys_account_id
     *
     * @mbggenerated
     */
    public String getSysAccountId() {
        return sysAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade_flow.sys_account_id
     *
     * @param sysAccountId the value for tb_trade_flow.sys_account_id
     *
     * @mbggenerated
     */
    public void setSysAccountId(String sysAccountId) {
        this.sysAccountId = sysAccountId == null ? null : sysAccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade_flow.creator
     *
     * @return the value of tb_trade_flow.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade_flow.creator
     *
     * @param creator the value for tb_trade_flow.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade_flow.create_datetime
     *
     * @return the value of tb_trade_flow.create_datetime
     *
     * @mbggenerated
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade_flow.create_datetime
     *
     * @param createDatetime the value for tb_trade_flow.create_datetime
     *
     * @mbggenerated
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade_flow.score_num
     *
     * @return the value of tb_trade_flow.score_num
     *
     * @mbggenerated
     */
    public Integer getScoreNum() {
        return scoreNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade_flow.score_num
     *
     * @param scoreNum the value for tb_trade_flow.score_num
     *
     * @mbggenerated
     */
    public void setScoreNum(Integer scoreNum) {
        this.scoreNum = scoreNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade_flow.good_luck_coin_num
     *
     * @return the value of tb_trade_flow.good_luck_coin_num
     *
     * @mbggenerated
     */
    public Integer getGoodLuckCoinNum() {
        return goodLuckCoinNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade_flow.good_luck_coin_num
     *
     * @param goodLuckCoinNum the value for tb_trade_flow.good_luck_coin_num
     *
     * @mbggenerated
     */
    public void setGoodLuckCoinNum(Integer goodLuckCoinNum) {
        this.goodLuckCoinNum = goodLuckCoinNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade_flow.order_num
     *
     * @return the value of tb_trade_flow.order_num
     *
     * @mbggenerated
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade_flow.order_num
     *
     * @param orderNum the value for tb_trade_flow.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade_flow.trade_type
     *
     * @return the value of tb_trade_flow.trade_type
     *
     * @mbggenerated
     */
    public Integer getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade_flow.trade_type
     *
     * @param tradeType the value for tb_trade_flow.trade_type
     *
     * @mbggenerated
     */
    public void setTradeType(Integer tradeType) {
        this.tradeType = tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade_flow.batch_code
     *
     * @return the value of tb_trade_flow.batch_code
     *
     * @mbggenerated
     */
    public String getBatchCode() {
        return batchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade_flow.batch_code
     *
     * @param batchCode the value for tb_trade_flow.batch_code
     *
     * @mbggenerated
     */
    public void setBatchCode(String batchCode) {
        this.batchCode = batchCode == null ? null : batchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trade_flow
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TradeFlowBean other = (TradeFlowBean) that;
        return (this.getFlowId() == null ? other.getFlowId() == null : this.getFlowId().equals(other.getFlowId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getSysAccountId() == null ? other.getSysAccountId() == null : this.getSysAccountId().equals(other.getSysAccountId()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getCreateDatetime() == null ? other.getCreateDatetime() == null : this.getCreateDatetime().equals(other.getCreateDatetime()))
            && (this.getScoreNum() == null ? other.getScoreNum() == null : this.getScoreNum().equals(other.getScoreNum()))
            && (this.getGoodLuckCoinNum() == null ? other.getGoodLuckCoinNum() == null : this.getGoodLuckCoinNum().equals(other.getGoodLuckCoinNum()))
            && (this.getOrderNum() == null ? other.getOrderNum() == null : this.getOrderNum().equals(other.getOrderNum()))
            && (this.getTradeType() == null ? other.getTradeType() == null : this.getTradeType().equals(other.getTradeType()))
            && (this.getBatchCode() == null ? other.getBatchCode() == null : this.getBatchCode().equals(other.getBatchCode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trade_flow
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFlowId() == null) ? 0 : getFlowId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getSysAccountId() == null) ? 0 : getSysAccountId().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getCreateDatetime() == null) ? 0 : getCreateDatetime().hashCode());
        result = prime * result + ((getScoreNum() == null) ? 0 : getScoreNum().hashCode());
        result = prime * result + ((getGoodLuckCoinNum() == null) ? 0 : getGoodLuckCoinNum().hashCode());
        result = prime * result + ((getOrderNum() == null) ? 0 : getOrderNum().hashCode());
        result = prime * result + ((getTradeType() == null) ? 0 : getTradeType().hashCode());
        result = prime * result + ((getBatchCode() == null) ? 0 : getBatchCode().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trade_flow
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", flowId=").append(flowId);
        sb.append(", userId=").append(userId);
        sb.append(", sysAccountId=").append(sysAccountId);
        sb.append(", creator=").append(creator);
        sb.append(", createDatetime=").append(createDatetime);
        sb.append(", scoreNum=").append(scoreNum);
        sb.append(", goodLuckCoinNum=").append(goodLuckCoinNum);
        sb.append(", orderNum=").append(orderNum);
        sb.append(", tradeType=").append(tradeType);
        sb.append(", batchCode=").append(batchCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}