package com.hundsun.internet.billingsystem.model;

import java.io.Serializable;

public class UserDatumBeanKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_datum.datum_id
     *
     * @mbggenerated
     */
    private String datumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_datum.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user_datum
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_datum.datum_id
     *
     * @return the value of tb_user_datum.datum_id
     *
     * @mbggenerated
     */
    public String getDatumId() {
        return datumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_datum.datum_id
     *
     * @param datumId the value for tb_user_datum.datum_id
     *
     * @mbggenerated
     */
    public void setDatumId(String datumId) {
        this.datumId = datumId == null ? null : datumId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_datum.user_id
     *
     * @return the value of tb_user_datum.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_datum.user_id
     *
     * @param userId the value for tb_user_datum.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_datum
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserDatumBeanKey other = (UserDatumBeanKey) that;
        return (this.getDatumId() == null ? other.getDatumId() == null : this.getDatumId().equals(other.getDatumId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_datum
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDatumId() == null) ? 0 : getDatumId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_datum
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", datumId=").append(datumId);
        sb.append(", userId=").append(userId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}