package com.hundsun.internet.billingsystem.dao;

import com.hundsun.internet.billingsystem.model.DatumBean;
import com.hundsun.internet.billingsystem.model.DatumBeanCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DatumBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_datum
     *
     * @mbggenerated
     */
    int countByExample(DatumBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_datum
     *
     * @mbggenerated
     */
    int deleteByExample(DatumBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_datum
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String datumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_datum
     *
     * @mbggenerated
     */
    int insert(DatumBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_datum
     *
     * @mbggenerated
     */
    int insertSelective(DatumBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_datum
     *
     * @mbggenerated
     */
    List<DatumBean> selectByExampleWithRowbounds(DatumBeanCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_datum
     *
     * @mbggenerated
     */
    List<DatumBean> selectByExample(DatumBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_datum
     *
     * @mbggenerated
     */
    DatumBean selectByPrimaryKey(String datumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_datum
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DatumBean record, @Param("example") DatumBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_datum
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DatumBean record, @Param("example") DatumBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_datum
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DatumBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_datum
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DatumBean record);
}