package com.hundsun.internet.billingsystem.dao;

import com.hundsun.internet.billingsystem.model.ScoreBean;
import com.hundsun.internet.billingsystem.model.ScoreBeanCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ScoreBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score
     *
     * @mbggenerated
     */
    int countByExample(ScoreBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score
     *
     * @mbggenerated
     */
    int deleteByExample(ScoreBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score
     *
     * @mbggenerated
     */
    int insert(ScoreBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score
     *
     * @mbggenerated
     */
    int insertSelective(ScoreBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score
     *
     * @mbggenerated
     */
    List<ScoreBean> selectByExampleWithRowbounds(ScoreBeanCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score
     *
     * @mbggenerated
     */
    List<ScoreBean> selectByExample(ScoreBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score
     *
     * @mbggenerated
     */
    ScoreBean selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ScoreBean record, @Param("example") ScoreBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ScoreBean record, @Param("example") ScoreBeanCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ScoreBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_score
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ScoreBean record);
}